export default {
  INIT_APP: 'INIT_APP',
  INIT_APP_SUCCESS: 'INIT_APP_SUCCESS',
  //
  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  //
  SET_CONTACT: 'SET_CONTACT',
  SET_CONTACT_SUCCESS: 'SET_CONTACT_SUCCESS',
  //
  SET_POSITION: 'SET_POSITION',
  SET_POSITION_SUCCESS: 'SET_POSITION_SUCCESS',
  //
  GET_MESSAGE_CONTENT: 'GET_MESSAGE_CONTENT',
  GET_MESSAGE_CONTENT_SUCCESS: 'GET_MESSAGE_CONTENT_SUCCESS',
  SET_MESSAGE_CONTENT: 'SET_MESSAGE_CONTENT',
  SET_MESSAGE_CONTENT_SUCCESS: 'SET_MESSAGE_CONTENT_SUCCESS',
  UPDATE_MESSAGE_CONTENT: 'UPDATE_MESSAGE_CONTENT',
  UPDATE_MESSAGE_CONTENT_SUCCESS: 'UPDATE_MESSAGE_CONTENT_SUCCESS',
  DELETE_MESSAGE_CONTENT: 'DELETE_MESSAGE_CONTENT',
  DELETE_MESSAGE_CONTENT_SUCCESS: 'DELETE_MESSAGE_CONTENT_SUCCESS',
}

export const contactType = {
  MYSELF: 'MYSELF',
  FIRST: 'FIRST',
}
