export default {
  GET_CONTACT: 'GET_CONTACT',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  //
  SET_CONTACT: 'SET_CONTACT',
  SET_CONTACT_SUCCESS: 'SET_CONTACT_SUCCESS',
}

export const contactType = {
  MYSELF: 'MYSELF',
  FIRST: 'FIRST',
}
